import { initStrudel, evaluate, hush, getAudioContext, samples } from "@strudel/web";

// Background music — live-coded Strudel patterns played in-browser (NO wav/mp3 file). Synth voices
// (saw/sine/tri/square) are generated by WebAudio; the RolandTR808/909 drums stream as samples from
// Strudel's default sample repos at runtime. Two tracks: a soft LOBBY ambience and an energetic IN-GAME
// loop. Browsers block audio until a user gesture, so the tracks only start from inside the click that
// enters the lobby / the JOIN click — both valid gestures.

// morning tech-house · deeper, cleaner, loops forever (user-authored). NOTE: authored with `$:` multi-patterns
// in the REPL; expressed here as ONE stack(...) so the master .gain() (volume slider) chains onto the end.
const LOBBY_PATTERN = String.raw`
setcps(122/60/4)                    // ~122 bpm

stack(
  // warm sustained chords — Cmaj7 · Am7 · Fmaj7 · G, smooth pads not stabs
  note("<[e4,g4,b4] [c4,e4,g4] [f4,a4,c5] [d4,g4,b4]>")
    .s("sawtooth")
    .lpf(1400).lpq(1)                 // rolled off = mellow, not bright/toony
    .attack(0.15).release(0.6)        // soft swell instead of plucky pop
    .gain(0.35)
    .room(0.4).roomsize(3),

  // rolling tech-house bassline — off-beat, deep and round
  note("<[~ c2 ~ c2 ~ c2 ~ c2] [~ a1 ~ a1 ~ a1 ~ a1] [~ f1 ~ f1 ~ f1 ~ f1] [~ g1 ~ g1 ~ g1 ~ g1]>")
    .s("sawtooth")
    .lpf(520).lpq(3)                  // deeper, less buzzy
    .attack(0.008).release(0.14)
    .gain(0.8),

  // subtle high shimmer — very sparse, no melody-toy feel
  note("<c6 e6 a5 g6>")
    .s("triangle")
    .lpf(4000)
    .gain(0.22)
    .attack(0.01).release(0.4)
    .room(0.45).roomsize(4)
    .degradeBy(0.5),

  // clean tech-house groove
  stack(
    s("bd*4").gain(0.9),
    s("~ cp ~ cp").gain(0.35),        // softer clap
    s("[~ hh]*4").gain(0.32).lpf(6000), // off-beat hats, less crisp
    s("~ ~ oh ~").gain(0.22)
  )
  .bank("RolandTR909")
  .swingBy(1/8, 8)                    // subtler shuffle
)
`;

const GAME_PATTERN = String.raw`
setcpm(134/4)

// energetic but not too heavy drums
let drums = stack(
  s("bd*4").bank("RolandTR909").gain(.68),
  s("~ cp ~ cp").bank("RolandTR808").gain(.38),
  s("hh*8").bank("RolandTR909").gain(.16),
  s("~ oh ~ oh").bank("RolandTR909").gain(.13)
)

// bouncy tech-house bass, filtered so it's not too harsh
let bass = note("d#2 ~ d#2 f#2 d#2 ~ c#2 b1")
  .s("sawtooth")
  .lpf(230)
  .release(.1)
  .gain(.48)

// catchy playful arcade hook
let hook = note("d#5 f#5 a#5 ~ c#6 a#5 f#5 ~")
  .s("triangle")
  .release(.09)
  .delay(.16)
  .room(.28)
  .gain(.24)

// small synth stab for tech-house feel
let stab = note("d#4 ~ ~ f#4 ~ a#4 ~ c#5")
  .s("square")
  .lpf(700)
  .release(.08)
  .gain(.14)
  .room(.25)

// little hip-hop style fill
let fill = s("~ ~ [cp cp] ~")
  .bank("RolandTR808")
  .gain(.25)

// arcade sparkle, very light
let sparkle = note("d#6 ~ f#6 ~ a#6 c#7 ~ a#6")
  .s("sine")
  .gain(.08)
  .room(.45)

// evolving in-game loop
arrange(
  [4, stack(drums, bass)],
  [4, stack(drums, bass, hook)],
  [8, stack(drums, bass, hook, stab)],
  [4, stack(drums, bass, fill)],
  [8, stack(drums, bass, hook, stab, sparkle)],
  [4, stack(drums, bass, hook, fill)],
  [8, stack(drums, bass, hook, stab, sparkle)]
)
`;

// LAST MAN STANDING — "Samurai Jack" taiko-driven dark electronica (user-authored).
const LMS_PATTERN = String.raw`
setcpm(100/4)   // 100 bpm — heavy driving gait

// === DRUMS: electronic pulse, half-time backbeat ===
let drums = stack(
  s("bd ~ ~ bd ~ ~ bd ~").gain(0.9),
  s("~ ~ ~ ~ sd ~ ~ ~").gain(0.7).room(0.25),
  s("hh*16").gain("0.2 0.1").pan(sine.range(0.4,0.6))
).bank("RolandTR909").room(0.12)

// === TAIKO: tribal heartbeat — tuned sine boom (built-in synth) ===
let taiko = note("d2 ~ d2 d2 ~ d2 ~ ~")
  .sound("sine").attack(0.001).decay(0.16).sustain(0).release(0.12).shape(0.3).gain(0.72).room(0.3)

// === TOMS: melodic fill rolls for tension — pitched triangle toms ===
let toms = note("d3 a2 d3 f3 a3 f3 a2 d3")
  .sound("triangle").attack(0.001).decay(0.18).sustain(0).release(0.2).gain(0.42).room(0.35)

// === BASS: dark synth pulse — softer, lower filter floor, less rumble ===
let bass = note("d1*8")
  .sound("sawtooth").lpf(sine.range(220,800).slow(8)).lpq(6)
  .release(0.12).gain(0.38).shape(0.2)

// === KOTO: eastern plucked motif (D minor pentatonic) — triangle pluck ===
let koto = note("<[d4 ~ f4 ~ g4 ~ a4 ~] [a4 ~ g4 ~ f4 ~ d4 ~]>")
  .sound("triangle").attack(0.001).decay(0.25).sustain(0).release(0.12)
  .gain(0.42).room(0.4).delay(0.2).delaytime(0.375)

// === SHAKUHACHI: breathy bamboo-flute lead — sine + vibrato ===
let flute = note("<[~ ~ a4 ~ ~ c5 d5 ~] [~ ~ a4 ~ ~ g4 f4 ~]>")
  .sound("sine").gain(0.34).attack(0.08).release(0.4).vib(4).lpf(2200).room(0.55)

// === PAD: dark modal swell — filtered saw ===
let pad = note("<[d2,a2,d3] [bb1,f2,bb2]>")
  .sound("sawtooth").lpf(600).gain(0.13).attack(2).release(3).room(0.7)

// === STAB: big-beat synth hit ===
let stab = note("<[d4,a4,d5] [bb3,f4,bb4]>")
  .struct("x ~ ~ ~ ~ ~ ~ ~")
  .sound("sawtooth").lpf(2000).lpq(4).release(0.3).gain(0.22).room(0.4)

arrange(
  [2,  stack(pad, flute)],                                // 1. quick eerie tease
  [4,  stack(pad, taiko, koto)],                          // 2. taiko wakes
  [8,  stack(drums, taiko, bass, koto)],                  // 3. DROP — electronic drive
  [8,  stack(drums, taiko, bass, koto, flute, stab)],     // 4. full — melody soars
  [4,  stack(pad, toms, flute)],                          // 5. breakdown — tom tension
  [8,  stack(drums, taiko, bass, koto, flute, stab)],     // 6. climax
  [4,  stack(pad, taiko)]                                 // 7. land it (loops back)
)
`;

// ROLL OUT — deep house with a tech-house roll (user-authored).
const ROLLOUT_PATTERN = String.raw`
setcpm(124/4)   // 124 bpm — house pocket

// === DRUMS: classic house 4-floor, offbeat hats, clap on 2&4 ===
let drums = stack(
  s("bd*4").gain(1),
  s("~ ~ cp ~ ~ ~ cp ~").gain(0.46).room(0.2),
  s("~ hh ~ hh ~ hh ~ hh").gain(0.32).pan(sine.range(0.42,0.58)),
  s("~ ~ ~ ~ ~ ~ ~ oh").gain(0.26),
  s("sh*16").gain(0.1)
).bank("RolandTR909").room(0.1)

// === BASS: rolling offbeat sub (the tech-house engine) ===
let bass = note("<[~ c2 ~ c2 ~ c2 ~ c2] [~ f1 ~ f1 ~ ab1 ~ c2]>")
  .sound("sawtooth").lpf(440).lpq(4).release(0.11).gain(0.6)

// === CHORDS: warm house pad-stabs, Cm9 → Fm9, sidechain pump ===
let chords = note("<[c3,eb3,g3,bb3,d4] [f3,ab3,c4,eb4,g4]>")
  .struct("~ x ~ ~ x ~ ~ x")
  .sound("triangle")
  .gain(isaw.range(0.3,0.46).fast(4))
  .lpf(2400).room(0.35).release(0.18)

// === PIANO: that classic house piano stab — triangle pluck ===
let piano = note("<[eb4,g4,bb4] [ab4,c5,eb5]>")
  .struct("~ ~ x ~ ~ ~ x ~")
  .sound("triangle").attack(0.001).decay(0.3).sustain(0.1).gain(0.28).room(0.3).release(0.4)

// === VOX-STAB: vowel-filtered saw faking a vocal chop ===
let vox = note("<[~ ~ ~ ~ g4 ~ ~ ~] [~ ~ ~ ~ c5 ~ ~ ~]>")
  .sound("sawtooth").vowel("<a e o>").lpf(1800).lpq(3)
  .gain(0.24).release(0.2).delay(0.3).delaytime(0.375).room(0.4)

// === PLUCK: high tech-house plink for top-end movement ===
let pluck = note("<c6 eb6 g6 bb6>")
  .struct("x ~ ~ x ~ x ~ ~")
  .sound("square").lpf(4000).release(0.06).gain(0.12)
  .delay(0.3).delaytime(0.1875).room(0.4)

// === PAD: deep warm swell for the airy stages — filtered saw ===
let pad = note("<[c2,c3,g3] [f2,c3,f3]>")
  .sound("sawtooth").lpf(700).gain(0.15).attack(1.5).release(2.5).room(0.6)

arrange(
  [8,  stack(drums, bass, pad)],
  [8,  stack(drums, bass, pad, chords)],
  [8,  stack(drums, bass, chords, piano, pluck)],
  [8,  stack(drums, bass, chords, piano, pluck, vox)],
  [4,  stack(bass, pad, chords, vox).lpf(saw.range(300,4000))],
  [8,  stack(drums, bass, chords, piano, pluck, vox)],
  [4,  stack(drums, bass, pad)]
)
`;

let initPromise: Promise<void> | null = null;
let token = 0;            // cancels an in-flight start() when stop()/switch/mute fires during init
let desiredCode: string | null = null; // the track that SHOULD be playing (null = nothing requested)
let musicVolume = 0.7;    // 0..1 slider value (settings; default 70%)
// The raw patterns are mixed loud, so the slider's 100% maps to this ACTUAL master gain ceiling (the old
// 16%-slider level the user found right). actualGain = musicVolume * MUSIC_GAIN_CEIL → 70% default ≈ 0.112.
const MUSIC_GAIN_CEIL = 0.16;

const MUTE_KEY = "musicMuted";
const loadMutedPref = (): boolean => { try { return localStorage.getItem(MUTE_KEY) === "1"; } catch { return false; } };
const saveMutedPref = (m: boolean): void => { try { localStorage.setItem(MUTE_KEY, m ? "1" : "0"); } catch { /* ignore */ } };
let muted = loadMutedPref();

// initStrudel() sets up the AudioContext + global pattern functions + the default sample prebake (same as
// strudel.cc, incl. the drum-machine banks). Run it once, lazily.
function ensureInit(): Promise<void> {
  if (!initPromise) {
    initPromise = (async () => {
      await initStrudel();
      // initStrudel()'s default prebake does NOT include the Roland drum-machine banks, so every
      // s(...).bank("RolandTR909"/"RolandTR808") was SILENT (the bug: tracks sounded wrong/"no drums").
      // Load the same drum-machine pack strudel.cc uses so the drums actually play.
      try {
        await samples("https://raw.githubusercontent.com/felixroos/dough-samples/main/tidal-drum-machines.json");
      } catch (e) {
        console.warn("[music] drum-machine samples failed to load:", e);
      }
      // The default prebake also lacks the `piano` sample set, so the lobby lo-fi track's .s("piano")
      // chords were SILENT ("[getTrigger] error: sound piano not found"). Load the Salamander piano pack.
      try {
        await samples("https://raw.githubusercontent.com/felixroos/dough-samples/main/piano.json");
      } catch (e) {
        console.warn("[music] piano samples failed to load:", e);
      }
      // NOTE: GM soundfonts (gm_*) were dropped — @strudel/web's bundled engine can't see instruments
      // registered by the standalone @strudel/soundfonts (separate audio-engine instance), so those layers
      // were silent. LMS/RollOut now use built-in synth voices that this engine renders natively.
    })();
  }
  return initPromise;
}

let delayTimer: ReturnType<typeof setTimeout> | null = null;
const clearDelay = (): void => { if (delayTimer) { clearTimeout(delayTimer); delayTimer = null; } };

// Play the desired track (unless muted). hush() first so a switch cleanly replaces the previous track
// (without this the lobby track kept playing in-game instead of swapping to GAME).
async function evalDesired(myToken: number): Promise<void> {
  try {
    await ensureInit();
    if (myToken !== token) return; // superseded
    try { await getAudioContext()?.resume?.(); } catch { /* sticky activation covers this */ }
    hush();
    // Append a master .gain() so the whole arrangement is scaled by the music-volume slider. The final
    // arrange(...) is the pattern expression, so `arrange(...)\n.gain(v)` multiplies every layer's gain.
    if (!muted && desiredCode) await evaluate(desiredCode + "\n.gain(" + (musicVolume * MUSIC_GAIN_CEIL) + ")");
  } catch (e) {
    console.warn("[music] failed to play track:", e);
  }
}

// Request a track (or null to stop). Stops the current track IMMEDIATELY (so JOIN silences the lobby at
// once); the new track starts after delayMs (the in-game track waits ~2s after JOIN before kicking in).
function request(code: string | null, delayMs = 0): void {
  desiredCode = code;
  const myToken = ++token;     // invalidate any in-flight eval / pending delayed start
  clearDelay();
  try { hush(); } catch { /* not inited */ }
  if (code == null) return;
  const fire = () => { if (myToken === token) void evalDesired(myToken); };
  if (delayMs > 0) { delayTimer = setTimeout(() => { delayTimer = null; fire(); }, delayMs); }
  else fire();
}

export const musicController = {
  /** Soft lobby ambience — call from within a user gesture (the click that enters the lobby). */
  startLobby(): void { request(LOBBY_PATTERN, 0); },
  /** In-game loop per mode: Spinner / Last Man Standing / Roll Out each get their own track. Unknown = silent.
   *  Now driven by the in-game countdown (fires on "3"), so it starts immediately by default. */
  startGame(mode?: string, delayMs: number = 0): void {
    const byMode: Record<string, string> = {
      spinner: GAME_PATTERN,
      lastman: LMS_PATTERN,
      rollout: ROLLOUT_PATTERN,
    };
    const code = byMode[mode ?? "spinner"] ?? null;
    request(code, delayMs);
  },
  /** Stop all music (e.g. back to the start screen). */
  stop(): void { request(null, 0); },

  /** Master music volume 0..1 (settings slider, default 0.7). Re-evals the current track to apply it. */
  setMusicVolume(v: number): void {
    musicVolume = Math.min(1, Math.max(0, Number.isFinite(v) ? v : 0.7));
    if (!muted && desiredCode) request(desiredCode, 0); // brief re-eval so the new master gain takes effect
  },

  isMuted(): boolean { return muted; },
  /** Mute/unmute BOTH tracks globally (persisted). Mute = silence now; unmute = resume the desired track. */
  setMuted(m: boolean): void {
    if (m === muted) return;
    muted = m; saveMutedPref(m);
    if (m) { token++; clearDelay(); try { hush(); } catch { /* ignore */ } }
    else request(desiredCode, 0);
  },
  /** Flip mute and return the new muted state. */
  toggle(): boolean { this.setMuted(!muted); return muted; },
};
